### ISSUE TITLE
Please update for tailwind-1.0?

### ISSUE THREAD

**Issue by ankush981** [adamwathan/vue-cli-tailwind-1.0#1]
Hello Adam! Since tailwind is no more in beta, maybe update this project as per the latest versions of everything? I understand it's trivial, but I had a really rough time trying to set up tailwind with Vue until I found this repo. With time, the packages here are kinda falling behind, so a refresh will be greatly appreciated! :innocent:

**Comment by adamwathan** [comment]
Nothing really to update other than running `yarn add tailwindcss@^1`. I wouldn't use this project as a true starting point for anything, I just made it to help someone on Discord one day 😅

To use Tailwind with vue-cli all you need to do is create a vue-cli project, install Tailwind (`npm install tailwindcss` or `yarn add tailwindcss`) and then add the `@tailwind` rules to your main `App` component: https://github.com/adamwathan/vue-cli-tailwind-1.0/blob/master/src/App.vue#L18-L22

**Comment by ankush981** [comment]
Oh, okay. Never mind! :smile: 

But in the example you linked, do I dump in my styles and components into the Appp.vue's `style` tags? Or is there a better way to organize this? I'm sorry if it sounds like I'm bothering you for something too silly, but tailwind has been a real challenge to set up -- add to it the JavaScript fatigue and new tools popping up all the time (now there's PostCSS and PurgeCSS too :cry:) and it's one giant demotivation for us mere mortals. :laughing:
